//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWap.WS_MTraffic {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Mtraffic.vn/", ConfigurationName="WS_MTraffic.MTrafficSoap")]
    public interface MTrafficSoap {
        
        // CODEGEN: Generating message contract since element name Signature from namespace http://Mtraffic.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/Check", ReplyAction="*")]
        MyWap.WS_MTraffic.CheckResponse Check(MyWap.WS_MTraffic.CheckRequest request);
        
        // CODEGEN: Generating message contract since element name Signature from namespace http://Mtraffic.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/Reg", ReplyAction="*")]
        MyWap.WS_MTraffic.RegResponse Reg(MyWap.WS_MTraffic.RegRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check", Namespace="http://Mtraffic.vn/", Order=0)]
        public MyWap.WS_MTraffic.CheckRequestBody Body;
        
        public CheckRequest() {
        }
        
        public CheckRequest(MyWap.WS_MTraffic.CheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Mtraffic.vn/")]
    public partial class CheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int KeywordID;
        
        public CheckRequestBody() {
        }
        
        public CheckRequestBody(string Signature, int KeywordID) {
            this.Signature = Signature;
            this.KeywordID = KeywordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckResponse", Namespace="http://Mtraffic.vn/", Order=0)]
        public MyWap.WS_MTraffic.CheckResponseBody Body;
        
        public CheckResponse() {
        }
        
        public CheckResponse(MyWap.WS_MTraffic.CheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Mtraffic.vn/")]
    public partial class CheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckResult;
        
        public CheckResponseBody() {
        }
        
        public CheckResponseBody(string CheckResult) {
            this.CheckResult = CheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reg", Namespace="http://Mtraffic.vn/", Order=0)]
        public MyWap.WS_MTraffic.RegRequestBody Body;
        
        public RegRequest() {
        }
        
        public RegRequest(MyWap.WS_MTraffic.RegRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Mtraffic.vn/")]
    public partial class RegRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChannelType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int KeywordID;
        
        public RegRequestBody() {
        }
        
        public RegRequestBody(int ChannelType, string Signature, int KeywordID) {
            this.ChannelType = ChannelType;
            this.Signature = Signature;
            this.KeywordID = KeywordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegResponse", Namespace="http://Mtraffic.vn/", Order=0)]
        public MyWap.WS_MTraffic.RegResponseBody Body;
        
        public RegResponse() {
        }
        
        public RegResponse(MyWap.WS_MTraffic.RegResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Mtraffic.vn/")]
    public partial class RegResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegResult;
        
        public RegResponseBody() {
        }
        
        public RegResponseBody(string RegResult) {
            this.RegResult = RegResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MTrafficSoapChannel : MyWap.WS_MTraffic.MTrafficSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MTrafficSoapClient : System.ServiceModel.ClientBase<MyWap.WS_MTraffic.MTrafficSoap>, MyWap.WS_MTraffic.MTrafficSoap {
        
        public MTrafficSoapClient() {
        }
        
        public MTrafficSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MTrafficSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTrafficSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTrafficSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWap.WS_MTraffic.CheckResponse MyWap.WS_MTraffic.MTrafficSoap.Check(MyWap.WS_MTraffic.CheckRequest request) {
            return base.Channel.Check(request);
        }
        
        public string Check(string Signature, int KeywordID) {
            MyWap.WS_MTraffic.CheckRequest inValue = new MyWap.WS_MTraffic.CheckRequest();
            inValue.Body = new MyWap.WS_MTraffic.CheckRequestBody();
            inValue.Body.Signature = Signature;
            inValue.Body.KeywordID = KeywordID;
            MyWap.WS_MTraffic.CheckResponse retVal = ((MyWap.WS_MTraffic.MTrafficSoap)(this)).Check(inValue);
            return retVal.Body.CheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWap.WS_MTraffic.RegResponse MyWap.WS_MTraffic.MTrafficSoap.Reg(MyWap.WS_MTraffic.RegRequest request) {
            return base.Channel.Reg(request);
        }
        
        public string Reg(int ChannelType, string Signature, int KeywordID) {
            MyWap.WS_MTraffic.RegRequest inValue = new MyWap.WS_MTraffic.RegRequest();
            inValue.Body = new MyWap.WS_MTraffic.RegRequestBody();
            inValue.Body.ChannelType = ChannelType;
            inValue.Body.Signature = Signature;
            inValue.Body.KeywordID = KeywordID;
            MyWap.WS_MTraffic.RegResponse retVal = ((MyWap.WS_MTraffic.MTrafficSoap)(this)).Reg(inValue);
            return retVal.Body.RegResult;
        }
    }
}
