//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCCare.WS_MTraffic {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Mtraffic.vn/", ConfigurationName="WS_MTraffic.MTrafficSoap")]
    public interface MTrafficSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/Check", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Check(string Signature, int KeywordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/Reg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Reg(int ChannelType, string Signature, int KeywordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/Reg_CMD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Reg_CMD(int ChannelType, string Signature, string CommandCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/Dereg_CMD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Dereg_CMD(int ChannelType, string Signature, string CommandCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/GetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInfo(string Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/Reg_VNP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Reg_VNP(string UserName, string IP, string Signature, MyCCare.WS_MTraffic.ChannelType mChannel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Mtraffic.vn/DeReg_VNP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeReg_VNP(string UserName, string IP, string Signature, MyCCare.WS_MTraffic.ChannelType mChannel);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mtraffic.vn/")]
    public enum ChannelType {
        
        /// <remarks/>
        SMS,
        
        /// <remarks/>
        IVR,
        
        /// <remarks/>
        WEB,
        
        /// <remarks/>
        WAP,
        
        /// <remarks/>
        USSD,
        
        /// <remarks/>
        CLIENT,
        
        /// <remarks/>
        API,
        
        /// <remarks/>
        UNSUB,
        
        /// <remarks/>
        CSKH,
        
        /// <remarks/>
        MAXRETRY,
        
        /// <remarks/>
        SUBNOTEXIST,
        
        /// <remarks/>
        SYSTEM,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MTrafficSoapChannel : MyCCare.WS_MTraffic.MTrafficSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MTrafficSoapClient : System.ServiceModel.ClientBase<MyCCare.WS_MTraffic.MTrafficSoap>, MyCCare.WS_MTraffic.MTrafficSoap {
        
        public MTrafficSoapClient() {
        }
        
        public MTrafficSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MTrafficSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTrafficSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTrafficSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Check(string Signature, int KeywordID) {
            return base.Channel.Check(Signature, KeywordID);
        }
        
        public string Reg(int ChannelType, string Signature, int KeywordID) {
            return base.Channel.Reg(ChannelType, Signature, KeywordID);
        }
        
        public string Reg_CMD(int ChannelType, string Signature, string CommandCode) {
            return base.Channel.Reg_CMD(ChannelType, Signature, CommandCode);
        }
        
        public string Dereg_CMD(int ChannelType, string Signature, string CommandCode) {
            return base.Channel.Dereg_CMD(ChannelType, Signature, CommandCode);
        }
        
        public System.Data.DataTable GetInfo(string Signature) {
            return base.Channel.GetInfo(Signature);
        }
        
        public string Reg_VNP(string UserName, string IP, string Signature, MyCCare.WS_MTraffic.ChannelType mChannel) {
            return base.Channel.Reg_VNP(UserName, IP, Signature, mChannel);
        }
        
        public string DeReg_VNP(string UserName, string IP, string Signature, MyCCare.WS_MTraffic.ChannelType mChannel) {
            return base.Channel.DeReg_VNP(UserName, IP, Signature, mChannel);
        }
    }
}
